server:
  port: 7777
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: xxoo
          predicates:
            - Path=/gateway/**
          uri: http://www.baidu.com
          filters: ##过滤几级
            - StripPrefix=1

        - id: provider
          predicates:
            - Path=/provider/**
          uri: lb://user-provider
          filters:
            - StripPrefix=1

      discovery:
        locator:
          ##开启从eureka 拉取服务列表  并自动映射
          enabled: true

##自定义负载均衡策略
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.gateway.MyRule

##注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/