spring:
  application:
    name: user-consumer
  # zipkin
  zipkin:
    base-url: http://localhost:9411/
  # sleuth 采样比例
  sleuth:
    sampler:
      rate: 1

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    # 刷新注册表间隔时间
    registry-fetch-interval-seconds: 10
    enabled: true
    healthcheck:
      enabled: true
  instance:
    # 心跳续约时间
    lease-renewal-interval-in-seconds: 10
    # 缺失心跳过期时间
    lease-expiration-duration-in-seconds: 10

ribbon:
  # 连接超时时间
  ConnectTimeout: 1000
  # 业务逻辑超时时间
  ReadTimeout: 2000
  # 同一台实例最大重试次数，不包括首次调用
  MaxAutoRetries: 1
  # 重试负载均衡其他实例最大重试次数，不包括首次调用
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false

# 开启hystrix
feign:
  hystrix:
    enabled: true
# 使用dashboard
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
# 信号量隔离
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

---
server:
  port: 8022
spring:
  profiles: user-consumer-1

---
server:
  port: 8023
spring:
  profiles: user-consumer-2