spring:
  application:
    name: cloud-admin
  security:
    user:
      name: root
      password: root
  # 邮件设置
  mail:
    host: smtp.qq.com
    username: 806463905
    password: zpyagkswzpmhbdbg
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
#收件邮箱
spring.boot.admin.notify.mail.to: 806463905@qq.com
# 发件邮箱
spring.boot.admin.notify.mail.from: zhenhua.yan@capgemini.com

server:
  port: 8080